set(CMAKE_ASM_VERBOSE_FLAG "-v")

string(APPEND CMAKE_ASM_FLAGS_INIT " ")
string(APPEND CMAKE_ASM_FLAGS_DEBUG_INIT " -g")
string(APPEND CMAKE_ASM_FLAGS_MINSIZEREL_INIT " -Os -DNDEBUG")
string(APPEND CMAKE_ASM_FLAGS_RELEASE_INIT " -O3 -DNDEBUG")
string(APPEND CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT " -O2 -g -DNDEBUG")

if(UNIX)
  set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S)
else()
  set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm)
endif()
